export const ADD = 'ADD';
export const REMOVE = 'REMOVE';
export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const ADDTO_COINS = 'ADDTO_COINS';
export const CHANGE_GRAPH_PERIOD = 'CHANGE_GRAPH_PERIOD';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const CHANGE_GLOBAL_PERCENT_CHANGE = 'CHANGE_GLOBAL_PERCENT_CHANGE';
export const TOGGLE_FULLPAGEGRAPH = 'TOGGLE_FULLPAGEGRAPH';